### ISSUE TITLE
Landingpage navbar ist zu breit und verursacht horizontale Scrollbar

### ISSUE THREAD

**Issue by coeys** [stefan-hinterhoelzl/DiversIT#25]
Vermutlich padding rechts zu entfernen

**Comment by deutho** [comment]
Problem liegt nicht in der Navbar.
hab rumgespielt und rausgefunden dass es an den Komponeten welche in der Langingpage eingebunden sind liegt.

wenn man die Komponenten app-mentor-spotlight, app-job-profiles und app-mission auskommentiert und nur das Banner und die Navbar behält verschwindet der horizontale scroll. Lässt man auch nur einen der Komponenten drin, ist die Scrollbar da.

einfach max-width auf den wrapper div zu setzen hat nicht funktioniert.
