### ISSUE TITLE
Speichern der Profilsettings nicht mehr möglich

### ISSUE THREAD

**Issue by deutho** [stefan-hinterhoelzl/DiversIT#31]
Hab mir den Main heute morgen geholt, und jetzt ist das Speichern der Profilsettings nicht mehr möglich.

Hat gestern jmd am userModel rumgespielt? oder an der Methode selbst?

Da ich davon ausgeh, dass ich es diesmal nicht war öffne ich hier mal ein Issue. 
(Schätze Stefan oder Gerald hatte hier die Finger drin?)

Der Error in der Konsole:
![image](https://user-images.githubusercontent.com/59829810/144007753-0ca5b589-4186-4816-a7f3-451644a6ea7e.png)

**Comment by k11812401** [comment]
Hab vergessen das neue Feld "notifications" im User-Model bei den bestehenden Benutzer in der Firestore DB nachzuziehen ... ist nun erledigt ... somit sollte auch der Felher erledigt sein!
